#!/bin/bash -


if [ $(uname -i) == "aarch64" ];
then
    echo "On Arm machine"
    M5_ADDR=0x10010000
else
    echo "On x86 machine"
    M5_ADDR=0xffff0000
fi


function gem5_run() {
    # ====
    # gem5 init service
    # ====
    #
    # Try to read in a run script from the host system.
    # For gem5 use the special magic instruction `m5 readfile`
    #
    echo "In gem5"
    # If there is a script, execute the script and then exit the simulation
    chmod 755 /tmp/script
    /tmp/script || true
    echo "Done running script, exiting."
    rm -f /tmp/script
    m5 --addr=$M5_ADDR exit
}


function qemu_run() {
    # ====
    # Qemu run service
    # ====
    #
    # Try to read in a run script from the host system.
    # For qemu we will try to get the file from an
    # HTTP server running on the host port 3003.
    #
    #

    curl "http://10.0.2.2:3003/run.sh" -f -o /tmp/script

    if [ 0 -eq $? ];
    then
        echo "Found file server in qemu."
        echo "Run script found... run it."
        chmod 755 /tmp/script

        # If there is a script, execute the script and then shutdown the machine
        /tmp/script || true
        echo "Done running script, exiting."
        rm -f /tmp/script
    else
        echo "No file server found"
    fi
}


## First try to read an init script with the m5 tool
/sbin/m5 --addr=$M5_ADDR readfile > /tmp/script
if [ -s /tmp/script ]; then
    # Successful read script
    # We are in gem5
    gem5_run
else
    # Read was not successful
    # Try to read script from file server
    qemu_run
fi